package: 
    name: xai
    version: "0.1.0"

python:
    - 3.6
    - 3.7
    - 3.8

build:
    number: 1
    script: python setup.py install

about:
    home: https://github.com/EthicalML/xai
    license: MIT
    license_file: LICENSE
    summary: XAI - An eXplainability toolbox for machine learning

extra:
    maintainers:
        - Alejandro Saucedo <a@ethical.institute>

source: 
    git_url: https://github.com/EthicalML/xai
    git_rev: master

channels:
    - conda-forge
    - defaults

requirements:
    build:
        - python
        - setuptools
        - pandas
        - matplotlib
        - numpy
        - scipy
        - scikit-learn
        - python-dateutil
        - pytz
        - pyparsing
        - cycler
        - kiwisolver
        - six

    run:
        - python
        - setuptools
        - pandas
        - matplotlib
        - numpy
        - scipy
        - scikit-learn
        - python-dateutil
        - pytz
        - pyparsing
        - cycler
        - kiwisolver
        - six

